# Generated by Django 3.1.2 on 2022-12-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dblucy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, default=' ', max_length=50)),
                ('sound', models.CharField(blank=True, default=' ', max_length=100)),
                ('bgcolor', models.CharField(blank=True, default=' ', max_length=50)),
                ('textsize', models.CharField(blank=True, default=' ', max_length=50)),
                ('type', models.CharField(blank=True, default=' ', max_length=50)),
                ('status', models.CharField(blank=True, default=' ', max_length=50)),
                ('data', models.CharField(blank=True, default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='dbtoeic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('name', models.CharField(default='', max_length=30)),
                ('chinese', models.CharField(max_length=50)),
                ('relate', models.CharField(blank=True, default='', max_length=50)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('level', models.IntegerField(blank=True, default=0)),
                ('toune', models.CharField(blank=True, default='', max_length=100)),
                ('sound', models.CharField(blank=True, default='', max_length=200)),
                ('wrong', models.IntegerField(blank=True, default=0)),
                ('standard', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
